spring.application.name=coreservices

#Server Port
server.port=8001

#PostgreSQL Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d8nnvhr7uimc73a33m00-a.oregon-postgres.render.com:5432/ps_29
spring.datasource.username=ps_29_user
spring.datasource.password=0GQikQOUy1FZzMmCsYJVeHvCxZy804CY

#JPA Configuration
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SpringDoc Startup Warnings Suppression
logging.level.org.springdoc.core.events.SpringDocAppInitializer=error